---
- name: Ensure 'man' directory exists.
  ansible.builtin.file:  # noqa risky-file-permissions
    path: /usr/share/man/man1
    state: directory
    mode: '0755'
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_major_version | int >= 18

- name: Ensure Java is installed.
  ansible.builtin.apt:
    name: "{{ java_packages }}"
    state: present
